[package]
name = "tron_macro"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"

[lib]
proc-macro = true
