[package]
name = "tron_macro"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = "2.0.57"

[lib]
proc-macro = true


